defmodule Helper.Countries do
  alias Helper.Country, as: Country

  @countries [
    %Country{iso: "AD", name: "Andorra"},
    %Country{iso: "AE", name: "United Arab Emirates"},
    %Country{iso: "AF", name: "Afghanistan"},
    %Country{iso: "AG", name: "Antigua and Barbuda"},
    %Country{iso: "AI", name: "Anguilla"},
    %Country{iso: "AL", name: "Albania"},
    %Country{iso: "AM", name: "Armenia"},
    %Country{iso: "AN", name: "Netherlands Antilles"},
    %Country{iso: "AO", name: "Angola"},
    %Country{iso: "AR", name: "Argentina"},
    %Country{iso: "AS", name: "American Samoa"},
    %Country{iso: "AT", name: "Austria"},
    %Country{iso: "AU", name: "Australia"},
    %Country{iso: "AW", name: "Aruba"},
    %Country{iso: "AZ", name: "Azerbaijan"},
    %Country{iso: "BA", name: "Bosnia and Herzegovina"},
    %Country{iso: "BB", name: "Barbados"},
    %Country{iso: "BD", name: "Bangladesh"},
    %Country{iso: "BE", name: "Belgium"},
    %Country{iso: "BF", name: "Burkina Faso"},
    %Country{iso: "BG", name: "Bulgaria"},
    %Country{iso: "BH", name: "Bahrain"},
    %Country{iso: "BI", name: "Burundi"},
    %Country{iso: "BJ", name: "Benin"},
    %Country{iso: "BM", name: "Bermuda"},
    %Country{iso: "BN", name: "Brunei"},
    %Country{iso: "BO", name: "Bolivia"},
    %Country{iso: "BR", name: "Brazil"},
    %Country{iso: "BS", name: "Bahamas"},
    %Country{iso: "BT", name: "Bhutan"},
    %Country{iso: "BW", name: "Botswana"},
    %Country{iso: "BY", name: "Belarus"},
    %Country{iso: "BZ", name: "Belize"},
    %Country{iso: "CA", name: "Canada"},
    %Country{iso: "CD", name: "DR Congo"},
    %Country{iso: "CF", name: "Central Africa"},
    %Country{iso: "CG", name: "Congo"},
    %Country{iso: "CH", name: "Switzerland"},
    %Country{iso: "CI", name: "Ivory Coast"},
    %Country{iso: "CK", name: "Cook Islands"},
    %Country{iso: "CL", name: "Chile"},
    %Country{iso: "CM", name: "Cameroon"},
    %Country{iso: "CN", name: "China"},
    %Country{iso: "CO", name: "Colombia"},
    %Country{iso: "CR", name: "Costa Rica"},
    %Country{iso: "CU", name: "Cuba"},
    %Country{iso: "CV", name: "Cape Verde"},
    %Country{iso: "CW", name: "Curaçao"},
    %Country{iso: "CY", name: "Cyprus"},
    %Country{iso: "CZ", name: "Czech Republic"},
    %Country{iso: "DE", name: "Germany"},
    %Country{iso: "DJ", name: "Djibouti"},
    %Country{iso: "DK", name: "Denmark"},
    %Country{iso: "DM", name: "Dominica"},
    %Country{iso: "DO", name: "Dominican Republic"},
    %Country{iso: "DZ", name: "Algeria"},
    %Country{iso: "EC", name: "Ecuador"},
    %Country{iso: "EE", name: "Estonia"},
    %Country{iso: "EG", name: "Egypt"},
    %Country{iso: "ER", name: "Eritrea"},
    %Country{iso: "ES", name: "Spain"},
    %Country{iso: "ET", name: "Ethiopia"},
    %Country{iso: "FI", name: "Finland"},
    %Country{iso: "FJ", name: "Fiji"},
    %Country{iso: "FK", name: "Falkland Islands"},
    %Country{iso: "FM", name: "Micronesia"},
    %Country{iso: "FO", name: "Faroe Islands"},
    %Country{iso: "FR", name: "France"},
    %Country{iso: "GA", name: "Gabon"},
    %Country{iso: "GB", name: "United Kingdom"},
    %Country{iso: "GD", name: "Grenada"},
    %Country{iso: "GE", name: "Georgia"},
    %Country{iso: "GF", name: "French Guiana"},
    %Country{iso: "GG", name: "Guernsey"},
    %Country{iso: "GH", name: "Ghana"},
    %Country{iso: "GI", name: "Gibraltar"},
    %Country{iso: "GL", name: "Greenland"},
    %Country{iso: "GM", name: "Gambia"},
    %Country{iso: "GN", name: "Guinea"},
    %Country{iso: "GP", name: "Guadeloupe"},
    %Country{iso: "GQ", name: "Equatorial Guinea"},
    %Country{iso: "GR", name: "Greece"},
    %Country{iso: "GT", name: "Guatemala"},
    %Country{iso: "GU", name: "Guam"},
    %Country{iso: "GW", name: "Guinea-Bissau"},
    %Country{iso: "GY", name: "Guyana"},
    %Country{iso: "HK", name: "Hong Kong"},
    %Country{iso: "HN", name: "Honduras"},
    %Country{iso: "HR", name: "Croatia"},
    %Country{iso: "HT", name: "Haiti"},
    %Country{iso: "HU", name: "Hungary"},
    %Country{iso: "ID", name: "Indonesia"},
    %Country{iso: "IE", name: "Ireland"},
    %Country{iso: "IL", name: "Israel"},
    %Country{iso: "IN", name: "India"},
    %Country{iso: "IO", name: "British Indian Ocean Territory"},
    %Country{iso: "IQ", name: "Iraq"},
    %Country{iso: "IR", name: "Iran"},
    %Country{iso: "IS", name: "Iceland"},
    %Country{iso: "IT", name: "Italy"},
    %Country{iso: "JE", name: "Jersey"},
    %Country{iso: "JM", name: "Jamaica"},
    %Country{iso: "JO", name: "Jordan"},
    %Country{iso: "JP", name: "Japan"},
    %Country{iso: "KE", name: "Kenya"},
    %Country{iso: "KG", name: "Kyrgyzstan"},
    %Country{iso: "KH", name: "Cambodia"},
    %Country{iso: "KI", name: "Kiribati"},
    %Country{iso: "KM", name: "Comoros"},
    %Country{iso: "KN", name: "St Kitts and Nevis"},
    %Country{iso: "KP", name: "North Korea"},
    %Country{iso: "KR", name: "Korea Republic of"},
    %Country{iso: "KW", name: "Kuwait"},
    %Country{iso: "KY", name: "Cayman Islands"},
    %Country{iso: "KZ", name: "Kazakhstan"},
    %Country{iso: "LA", name: "Laos PDR"},
    %Country{iso: "LB", name: "Lebanon"},
    %Country{iso: "LC", name: "St Lucia"},
    %Country{iso: "LI", name: "Liechtenstein"},
    %Country{iso: "LK", name: "Sri Lanka"},
    %Country{iso: "LR", name: "Liberia"},
    %Country{iso: "LS", name: "Lesotho"},
    %Country{iso: "LT", name: "Lithuania"},
    %Country{iso: "LU", name: "Luxembourg"},
    %Country{iso: "LV", name: "Latvia"},
    %Country{iso: "LY", name: "Libya"},
    %Country{iso: "MA", name: "Morocco"},
    %Country{iso: "MC", name: "Monaco"},
    %Country{iso: "MD", name: "Moldova"},
    %Country{iso: "ME", name: "Montenegro"},
    %Country{iso: "MG", name: "Madagascar"},
    %Country{iso: "MH", name: "Marshall Islands"},
    %Country{iso: "MK", name: "Macedonia"},
    %Country{iso: "ML", name: "Mali"},
    %Country{iso: "MM", name: "Myanmar"},
    %Country{iso: "MN", name: "Mongolia"},
    %Country{iso: "MO", name: "Macau"},
    %Country{iso: "MQ", name: "Martinique"},
    %Country{iso: "MR", name: "Mauritania"},
    %Country{iso: "MS", name: "Montserrat"},
    %Country{iso: "MT", name: "Malta"},
    %Country{iso: "MU", name: "Mauritius"},
    %Country{iso: "MV", name: "Maldives"},
    %Country{iso: "MW", name: "Malawi"},
    %Country{iso: "MX", name: "Mexico"},
    %Country{iso: "MY", name: "Malaysia"},
    %Country{iso: "MZ", name: "Mozambique"},
    %Country{iso: "NA", name: "Namibia"},
    %Country{iso: "NC", name: "New Caledonia"},
    %Country{iso: "NE", name: "Niger"},
    %Country{iso: "NF", name: "Norfolk Island"},
    %Country{iso: "NG", name: "Nigeria"},
    %Country{iso: "NI", name: "Nicaragua"},
    %Country{iso: "NL", name: "Netherlands"},
    %Country{iso: "NO", name: "Norway"},
    %Country{iso: "NP", name: "Nepal"},
    %Country{iso: "NR", name: "Nauru"},
    %Country{iso: "NU", name: "Niue"},
    %Country{iso: "NZ", name: "New Zealand"},
    %Country{iso: "OM", name: "Oman"},
    %Country{iso: "PA", name: "Panama"},
    %Country{iso: "PE", name: "Peru"},
    %Country{iso: "PF", name: "French Polynesia"},
    %Country{iso: "PG", name: "Papua New Guinea"},
    %Country{iso: "PH", name: "Philippines"},
    %Country{iso: "PK", name: "Pakistan"},
    %Country{iso: "PL", name: "Poland"},
    %Country{iso: "PM", name: "St Pierre and Miquelon"},
    %Country{iso: "PR", name: "Puerto Rico"},
    %Country{iso: "PS", name: "Palestinian Territory"},
    %Country{iso: "PT", name: "Portugal"},
    %Country{iso: "PW", name: "Palau"},
    %Country{iso: "PY", name: "Paraguay"},
    %Country{iso: "QA", name: "Qatar"},
    %Country{iso: "RE", name: "Reunion/Mayotte"},
    %Country{iso: "RO", name: "Romania"},
    %Country{iso: "RS", name: "Serbia"},
    %Country{iso: "RU", name: "Russia"},
    %Country{iso: "RW", name: "Rwanda"},
    %Country{iso: "SA", name: "Saudi Arabia"},
    %Country{iso: "SB", name: "Solomon Islands"},
    %Country{iso: "SC", name: "Seychelles"},
    %Country{iso: "SD", name: "Sudan"},
    %Country{iso: "SE", name: "Sweden"},
    %Country{iso: "SG", name: "Singapore"},
    %Country{iso: "SH", name: "Saint Helena and Tristan da Cunha"},
    %Country{iso: "SI", name: "Slovenia"},
    %Country{iso: "SK", name: "Slovakia"},
    %Country{iso: "SL", name: "Sierra Leone"},
    %Country{iso: "SM", name: "San Marino"},
    %Country{iso: "SN", name: "Senegal"},
    %Country{iso: "SO", name: "Somalia"},
    %Country{iso: "SR", name: "Suriname"},
    %Country{iso: "SS", name: "South Sudan"},
    %Country{iso: "ST", name: "Sao Tome and Principe"},
    %Country{iso: "SV", name: "El Salvador"},
    %Country{iso: "SY", name: "Syria"},
    %Country{iso: "SZ", name: "Swaziland"},
    %Country{iso: "TC", name: "Turks and Caicos Islands"},
    %Country{iso: "TD", name: "Chad"},
    %Country{iso: "TG", name: "Togo"},
    %Country{iso: "TH", name: "Thailand"},
    %Country{iso: "TJ", name: "Tajikistan"},
    %Country{iso: "TK", name: "Tokelau"},
    %Country{iso: "TL", name: "East Timor"},
    %Country{iso: "TM", name: "Turkmenistan"},
    %Country{iso: "TN", name: "Tunisia"},
    %Country{iso: "TO", name: "Tonga"},
    %Country{iso: "TR", name: "Turkey"},
    %Country{iso: "TT", name: "Trinidad and Tobago"},
    %Country{iso: "TV", name: "Tuvalu"},
    %Country{iso: "TW", name: "Taiwan"},
    %Country{iso: "TZ", name: "Tanzania"},
    %Country{iso: "UA", name: "Ukraine"},
    %Country{iso: "UG", name: "Uganda"},
    %Country{iso: "US", name: "United States"},
    %Country{iso: "UY", name: "Uruguay"},
    %Country{iso: "UZ", name: "Uzbekistan"},
    %Country{iso: "VC", name: "St Vincent Grenadines"},
    %Country{iso: "VE", name: "Venezuela"},
    %Country{iso: "VG", name: "Virgin Islands"},
    %Country{iso: "VI", name: "Virgin Islands"},
    %Country{iso: "VN", name: "Vietnam"},
    %Country{iso: "VU", name: "Vanuatu"},
    %Country{iso: "WF", name: "Wallis and Futuna"},
    %Country{iso: "WS", name: "Samoa"},
    %Country{iso: "XK", name: "Kosovo"},
    %Country{iso: "YE", name: "Yemen"},
    %Country{iso: "ZA", name: "South Africa"},
    %Country{iso: "ZM", name: "Zambia"},
    %Country{iso: "ZW", name: "Zimbabwe"},
    %Country{iso: "BQ", name: "Bonaire, Sint Eustatius and Saba"}
  ]

  def all, do: @countries

  def by_iso(iso) do
    @countries
    |> Enum.find(fn co -> co.iso == iso end)
  end
end
